export const GET_SHOWS_SUCCESS = "GET_SHOWS_SUCCESS";
export const GET_SHOWS_REJECTED = "GET_SHOWS_REJECTED";

export const GET_QUERY_ASYNC = "GET_QUERY_ASYNC";
export const GET_QUERY_TO_INITIAL = "GET_QUERY_TO_INITIAL";